version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
        environment:
            APP_ENV: local
            APP_DEBUG: true
            APP_URL: http://localhost:8000
            DB_CONNECTION: sqlite
            DB_DATABASE: /var/www/database/database.sqlite
        depends_on:
            - migrate
        extra_hosts:
            - "host.docker.internal:host-gateway"

    migrate:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
        command: >
            sh -c "php artisan migrate --force && php artisan storage:link"
